root@df39d6169e90:/tmp# hadoop jar hadoop-streaming-3.2.1.jar \
> -file autoinc_mapper1.py -mapper autoinc_mapper1.py \
> -file autoinc_reducer1.py -reducer autoinc_reducer1.py \ 
> -input /user/root/input/data.csv -output /output/all_accidents
2021-11-27 19:47:08,098 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
packageJobJar: [autoinc_mapper1.py, autoinc_reducer1.py, /tmp/hadoop-unjar2452785903685348455/] [] /tmp/streamjob3450734247344676540.jar tmpDir=null
2021-11-27 19:47:10,714 INFO client.RMProxy: Connecting to ResourceManager at resourcemanager/172.19.0.6:8032
2021-11-27 19:47:11,153 INFO client.AHSProxy: Connecting to Application History server at historyserver/172.19.0.5:10200
2021-11-27 19:47:11,212 INFO client.RMProxy: Connecting to ResourceManager at resourcemanager/172.19.0.6:8032
2021-11-27 19:47:11,214 INFO client.AHSProxy: Connecting to Application History server at historyserver/172.19.0.5:10200
2021-11-27 19:47:11,646 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /tmp/hadoop-yarn/staging/root/.staging/job_1638039735652_0002
2021-11-27 19:47:11,909 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2021-11-27 19:47:12,130 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2021-11-27 19:47:12,180 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2021-11-27 19:47:12,332 INFO mapred.FileInputFormat: Total input files to process : 1
2021-11-27 19:47:12,411 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2021-11-27 19:47:12,482 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2021-11-27 19:47:12,522 INFO mapreduce.JobSubmitter: number of splits:2
2021-11-27 19:47:12,963 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
2021-11-27 19:47:13,013 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1638039735652_0002
2021-11-27 19:47:13,013 INFO mapreduce.JobSubmitter: Executing with tokens: []
2021-11-27 19:47:13,471 INFO conf.Configuration: resource-types.xml not found
2021-11-27 19:47:13,472 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
2021-11-27 19:47:14,314 INFO impl.YarnClientImpl: Submitted application application_1638039735652_0002
2021-11-27 19:47:14,448 INFO mapreduce.Job: The url to track the job: http://resourcemanager:8088/proxy/application_1638039735652_0002/
2021-11-27 19:47:14,453 INFO mapreduce.Job: Running job: job_1638039735652_0002
2021-11-27 19:47:31,887 INFO mapreduce.Job: Job job_1638039735652_0002 running in uber mode : false
2021-11-27 19:47:31,896 INFO mapreduce.Job:  map 0% reduce 0%
2021-11-27 19:47:46,642 INFO mapreduce.Job: Task Id : attempt_1638039735652_0002_m_000000_0, Status : FAILED
Error: java.lang.RuntimeException: Error in configuring object
	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:113)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:79)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:462)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:174)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:168)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:110)
	... 9 more
Caused by: java.lang.RuntimeException: Error in configuring object
	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:113)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:79)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
	at org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:110)
	... 17 more
Caused by: java.lang.RuntimeException: configuration exception
	at org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:222)
	at org.apache.hadoop.streaming.PipeMapper.configure(PipeMapper.java:66)
	... 22 more
Caused by: java.io.IOException: Cannot run program "/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1638039735652_0002/container_e02_1638039735652_0002_01_000002/./autoinc_mapper1.py": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.apache.hadoop.streaming.PipeMapRed.configure(PipeMapRed.java:209)
	... 23 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 24 more
